### ISSUE TITLE
Implement SelfTargetExecutor to run YChaos on the same machine

### ISSUE THREAD

**Issue by shashankrnr32** [yahoo/ychaos#12]
## Is your proposal related to a problem?

Currently we have a [`MachineTargetExecutor`](https://github.com/yahoo/ychaos/blob/main/src/ychaos/core/executor/MachineTargetExecutor.py) which connects to the remote hosts via ansible to run the agents using Coordinator. Some of the agents doesn't require SSHing to the hosts. They can be run directly from the same machine where the tool is being executed. 

A simple example of this is the [SSL Certificate validation](https://github.com/yahoo/ychaos/blob/ebb4fb7e35ba06025287788b80c046fe2eaf3ce4/src/ychaos/agents/validation/certificate.py#L57)/HTTP Overload Agent (currently NA in the framework)

## What is the solution you are proposing?

Implement [SelfTargetExecutor](https://github.com/yahoo/ychaos/blob/main/src/ychaos/core/executor/SelfTargetExecutor.py) to run the YChaos coordinator right on the host where YChaos is being executed.

**Comment by shashankrnr32** [comment]
Starting this discussion, Here are the possible ways to implement SelfTargetExecutor. Refer to [MachineTargetExecutor](https://github.com/yahoo/ychaos/blob/main/src/ychaos/core/executor/MachineTargetExecutor.py) to know how its implemented using Ansible to SSH to hosts and run commands on the host.

1. We can write our own modules to run different tasks that is supposed to run for YChaos. For example, creation of Virtual Environment, installation of packages etc.
2. We can use the Ansible's `local_action` (Delegation of tasks) feature for the same. See docs, https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html. This implementation would mean we would be reusing most of the way we do things in MachineTargetExecutor. We can make use of the same Ansible modules for the same.

Add your thoughts in this thread @yahoo/ychaos-dev

**Comment by lakshmi-k05** [comment]
I think the second approach is better. Handling dependancies of packages would be simpler, as we would not need to update it here. Plus, reusing Ansible's modules will enable us to have the same functions for remote hosts as well as running locally. Easier to maintain as well

**Comment by shashankrnr32** [comment]
I agree. We can refactor MachineTargetExecutor to have common utility functions to delegate actions to the right target based on Ansible's features.

**Comment by shashankrnr32** [comment]
@AlfinST Can you please add documentation to the Self Target Executor and close this issue?
